### ISSUE TITLE
Why are some versions not included?

### ISSUE THREAD

**Issue by benjaminmesser** [pypi/stdlib-list#32]
Any reason why 3.1.5, 3.0.1, and pre-2.6 aren't included? Also why no 3.9? I'd be happy to add these myself, I just want to make sure that there's not some reason that they aren't being included.

Also any reason that 2.6 is not checked in `.travis.yml`?

**Comment by benjaminmesser** [comment]
Okay nevermind, [https://docs.travis-ci.com/user/languages/python/#python-versions](url) tells me why 2.6, 3.2, and 3.3 aren't run through Travis CI. But my other questions still stand.

**Comment by thebjorn** [comment]
3.9 is still in alpha, but I'm pretty sure that there are no philosophical reasons any of them are excluded (same with pypy and other python implementations - and other OSs too). Help, both in raising issues and especially PRs are always welcome :-)
