### ISSUE TITLE
Some extra (mostly tests?) modules included

### ISSUE THREAD

**Issue by thatch** [pypi/stdlib-list#35]
From a spot-check, there are some extra modules that don't end up in site-packages on a standard install.

```
ctypes.test.test_cfuncs
distutils.tests.test_build_scripts
test.badsyntax_pep3120
test.test_asyncio.test_futures
test.test_subprocess
json.re (on 2.7)
```

Most of these aren't going to pose a big problem for me, but considering top-level names only `test.*` will.  Would you accept a pull request that filters these (just `test.*` for now) in fetch?

**Comment by thatch** [comment]
On 3.9, there is a lib.libpython3 that is very problematic for usort's use of detecting stdlib top-level names.  I fixed and re-ran fetch with some small changes, and it's excluding some others, like posixpath now.  I think something has changed in the data upstream.

https://github.com/thatch/python-stdlib-list/commit/e38754009e1f0b34e9a3ededcdd2361cb05d65ed (and changes to fetch script in the couple of commits prior)

**Comment by thatch** [comment]
@CJ-Wright I saw your PR #39  -- looks like you didn't use stdlib_list.fetch for that?

**Comment by woodruffw** [comment]
Folding under #80.
