### ISSUE TITLE
possible missing packages for python 3.9 stdlib

### ISSUE THREAD

**Issue by alan-barzilay** [pypi/stdlib-list#45]
Hi! Sorry if I'm missing something obvious, but I'm looking at the lists of python 3.X stdlib packages and they all keep incrementing with each version released, except for [version 3.9](https://github.com/jackmaney/python-stdlib-list/blob/master/stdlib_list/lists/3.9.txt) where it plummets to 886 lines compared to the 1766 lines in [version 3.8](https://github.com/jackmaney/python-stdlib-list/blob/master/stdlib_list/lists/3.8.txt)

Are there any packages missing from the list of version 3.9? Or was there some sort of change in version 3.9 with how the stdlib works?

PS:  thank you so much for  your work on this project and on keeping it up to date!
I'm the new maintainer of [pipreqs](https://github.com/bndr/pipreqs) and I need to update our list of stdlib packages, this is saving so much of my time haha

**Comment by woodruffw** [comment]
Sorry for the delay here @alan-barzilay! I believe this has been addressed with #83; please let me know if you notice any other discrepancies.
