### ISSUE TITLE
Time for a new release with 3.10 and 3.11 support?

### ISSUE THREAD

**Issue by gforcada** [pypi/stdlib-list#55]
@jackmaney Thanks for this package! We are using it at https://github.com/reinout/z3c.dependencychecker and it is great! 💯 

It would be nice if there could be a new release with support for 3.10 and 3.11 🤩 

I could try to help if given instructions or permissions on pypi.

Are there any blockers that prevent such a release? Or is mostly available time? 😅

**Comment by ocefpaf** [comment]
This is built-in since py310. You can do:

```
builtin_modules = list(set(list(sys.stdlib_module_names) + list(sys.builtin_module_names)))
```

to get the same list one would get from `python-stdlib-list`.

We can implement that to help projects transition to py310/311 or we can quit cold turkey and no longer support python-stdlib-list for modern py>=3.10.

**Comment by gforcada** [comment]
@ocefpaf Oh cool! 👍🏾 I saw it on the release notes, but my first quick test (and actually late at night and quite tired) showed quite different results, so I thought this package was still more complete 😅 

a new release that only does this one liner might still be nice though. With a deprecation warning on top, so one can remove one dependency from 3.10 on wards with this little snippet 👍🏾

**Comment by ocefpaf** [comment]
> a new release that only does this one liner might still be nice though. With a deprecation warning on top, so one can remove one dependency from 3.10 on wards with this little snippet 👍🏾

I don't have time to work on that but I can review a PR that implements it if you re interested.

**Comment by gforcada** [comment]
I'm probably on you train as well, not so much time available, but I will give it a try! 🤞🏾 thanks! 🙏🏾

**Comment by arunpersaud** [comment]
It would also be great to update the home page and pypi page to reflect that you can do that now using sys.

**Comment by woodruffw** [comment]
Just to give a brief update here: we've coordinated with the original maintainer to transfer this project to the PyPI GitHub organization, and we'll plan a new release that contains stdlib lists for 3.10 and 3.11.

**Comment by ocefpaf** [comment]
Hey and thanks for kicking me out! That was a first.

My only planned PR to this package was to do the same we did in depfinfer, to use the built-in package list when that is available and slowly deprecated this package.

**Comment by woodruffw** [comment]
I'm currently working on this: #64 and #65 are automated list generations for 3.10 and 3.11, respectively.
