### ISSUE TITLE
Rocky project maintenance transition

### ISSUE THREAD

**Issue by ewdurbin** [pypi/stdlib-list#57]
I want to start by apologizing to @ocefpaf and @ericdill for the way that this all unfolded. It was certainly *not* the intention of anyone involved to impact you in this way, and I understand why you may be feeling dismissed or cast-aside as a result.

# What happened

My understanding (as one of four PyPI admins) is as follows:

1) An issue was filed on pypi/warehouse regarding how to handle the fact that `stdlib-list` hadn't seen a release in multiple years and was recently archived: https://github.com/pypi/warehouse/issues/13886
2) PyPI admins and a contributor considered the state of the project, our need for what it provides as part of running PyPI, and what could be done, selecting to consider adopting the project if the current owner was interested
3) As the repo was archived and issues could not be filed or responded to, it was decided to reach out directly to `@jackmaney`. This outreach included @woodruffw and 2/4 PyPI admins @di and @dstufft
4) `@jackmaney` successfully transferred the project to the pypi GitHub org via @dstufft
5) `@jackmaney` gave affirmative permission for @dstufft to transfer the project to the pypi PyPI org
6) @dstufft aligned the permissions on the GitHub and PyPI project with our standard permissions, in the process removing @ocefpaf and @ericdill from both places without notice

# How did it happen

This isn't how this should have gone and its clear that there were oversights in this process:

- Incomplete visibility among PyPI admins to what was occurring by only including 2/4 of the PyPI admins on the outreach in 3)
- A lack of follow up with the remaining maintainers @ocefpaf and @ericdill before proceeding to drop their roles on the GitHub repository and PyPI project

# What now?

@ocefpaf and @ericdill, we want to invite you back to your role as a maintainer of this project

Beyond that, I'm going to discuss with the PyPI administrators internally about what we can do to ensure that this kind of thing doesn't move at such a pace with such little internal visibility in the future.

---

Note, the previous project owner `@jackmaney` has been omitted from mention on this issue, as they are no longer interested in this project.

**Comment by dstufft** [comment]
I just want to apologize here on this issue as well for removing permissions without notice, that was on me.

**Comment by woodruffw** [comment]
I also want to offer an apology, as the person who offered to take over maintenance of this project: I performed the initial outreach to `@jackmaney`, and didn't rope all of the PyPI admins in. That was an oversight on my part, and I'm sorry for the stress it caused you.

**Comment by ericdill** [comment]
I’m with @ocefpaf on this one. I’m not interested in further collaboration at this time. Best of luck with the project.

**Comment by ewdurbin** [comment]
Understood, thanks for your responses.
